[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
ffi = false
solc_version = "0.8.26"
evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
